# Generated by Django 4.2.7

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company requesting demo', max_length=100)),
                ('first_name', models.CharField(help_text='First name of the contact person', max_length=50)),
                ('last_name', models.CharField(help_text='Last name of the contact person', max_length=50)),
                ('email', models.EmailField(help_text='Email address of the contact person', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Phone number of the contact person', max_length=20)),
                ('job_title', models.CharField(blank=True, help_text='Job title of the contact person', max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], help_text='Size of the company', max_length=50)),
                ('industry', models.CharField(blank=True, help_text='Industry or business sector', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Additional message or requirements')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('converted', 'Converted to Tenant'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the demo request', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes and status messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant created from this demo request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
