# Generated by Django 4.2.7 on 2025-08-18 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('user', 'Regular User')], default='user', help_text='User type determines default permissions', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or team', max_length=100)),
                ('job_title', models.CharField(blank=True, help_text='Job title or position', max_length=100)),
                ('is_tenant_admin', models.BooleanField(default=False, help_text='Whether this user is an admin for their tenant')),
                ('preferences', models.JSONField(default=dict, help_text='User-specific preferences and settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
