# Generated by Django 4.2.7 on 2025-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'Tenant User', 'verbose_name_plural': 'Tenant Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_tenant_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Tenant admin - has all permissions in this tenant'),
        ),
    ]
