# Generated by Django 4.2.7 on 2025-08-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='superuser',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='superuser',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='If True, can only view Django admin (no edit/delete permissions)'),
        ),
    ]
