# Generated by Django 5.2.5 on 2025-08-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('users', '0002_alter_customuser_department_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_updated', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Associated company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_created', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_contacts', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_updated', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags_created', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contacttagassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments_made', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contacttagassignment',
            name='contact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contacttagassignment',
            name='tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_assignments', to='contacts.contacttag'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='contacts_co_name_c7d502_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='contacts_co_industr_c7190e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='contacts_co_created_296db7_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='contacts_co_last_na_bb56ce_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contacts_co_email_25f973_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type'], name='contacts_co_contact_d678b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['score'], name='contacts_co_score_8eb180_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['created_at'], name='contacts_co_created_71b3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner'], name='contacts_co_owner_i_aa2753_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_contact_email_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_tag_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contacttagassignment',
            constraint=models.UniqueConstraint(fields=('contact', 'tag'), name='unique_contact_tag_assignment'),
        ),
    ]
