# Generated by Django 5.2.5 on 2025-08-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the role group', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the role group')),
                ('permission_codenames', models.JSONField(default=list, help_text='List of permission codenames assigned to this role group')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role group is currently active')),
                ('original_role_group_id', models.IntegerField(blank=True, help_text='ID of the original role group in public schema', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Role Group',
                'verbose_name_plural': 'Tenant Role Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is currently active')),
            ],
            options={
                'verbose_name': 'Tenant User Role',
                'verbose_name_plural': 'Tenant User Roles',
            },
        ),
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the role', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the role')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_group', models.ForeignKey(help_text='Role group this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenant_permissions.tenantrolegroup')),
            ],
            options={
                'verbose_name': 'Tenant Role',
                'verbose_name_plural': 'Tenant Roles',
                'ordering': ['role_group__name', 'name'],
            },
        ),
    ]
