# Generated by Django 4.2.7 on 2025-08-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the tenant organization'),
        ),
    ]
