# Generated by Django 4.2.7 on 2025-08-23 14:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_company_created_by_company_updated_by_and_more'),
        ('users', '0002_alter_customuser_department_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Opportunity name/title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the opportunity')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected deal value in currency units', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of this opportunity', max_length=10)),
                ('probability', models.DecimalField(decimal_places=2, default=0, help_text='Custom probability override (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, help_text='Expected closing date', null=True)),
                ('actual_close_date', models.DateField(blank=True, help_text='Actual closing date (when won/lost)', null=True)),
                ('lead_source', models.CharField(blank=True, help_text='How this opportunity was generated', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this opportunity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company associated with this opportunity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='contacts.company')),
                ('contact', models.ForeignKey(help_text='Primary contact for this opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='contacts.contact')),
                ('created_by', models.ForeignKey(help_text='User who created this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities_created', to='users.customuser')),
                ('owner', models.ForeignKey(help_text='Sales representative assigned to this opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='owned_opportunities', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Stage name (e.g., 'Qualified Lead', 'Proposal Sent')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this stage represents')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of stages (lower numbers first)')),
                ('probability', models.DecimalField(decimal_places=2, default=0, help_text='Expected close probability for this stage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_closed_won', models.BooleanField(default=False, help_text="Mark as a 'won' stage (deal is closed successfully)")),
                ('is_closed_lost', models.BooleanField(default=False, help_text="Mark as a 'lost' stage (deal is closed unsuccessfully)")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this stage is currently active')),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for UI display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_created', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Sales Stage',
                'verbose_name_plural': 'Sales Stages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('stage_changed', 'Stage Changed'), ('value_changed', 'Value Changed'), ('owner_changed', 'Owner Changed'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='updated', help_text='Type of action that occurred', max_length=20)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, help_text='Previous opportunity value', max_digits=12, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, help_text='New opportunity value', max_digits=12, null=True)),
                ('old_probability', models.DecimalField(blank=True, decimal_places=2, help_text='Previous probability', max_digits=5, null=True)),
                ('new_probability', models.DecimalField(blank=True, decimal_places=2, help_text='New probability', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser')),
                ('new_stage', models.ForeignKey(blank=True, help_text='New stage (for stage changes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_new_stage', to='opportunities.salesstage')),
                ('old_stage', models.ForeignKey(blank=True, help_text='Previous stage (for stage changes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_old_stage', to='opportunities.salesstage')),
                ('opportunity', models.ForeignKey(help_text='Opportunity this history entry relates to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity History',
                'verbose_name_plural': 'Opportunity Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(help_text='Current sales stage', on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.salesstage'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities_updated', to='users.customuser'),
        ),
        migrations.AddIndex(
            model_name='salesstage',
            index=models.Index(fields=['order'], name='opportuniti_order_e24622_idx'),
        ),
        migrations.AddIndex(
            model_name='salesstage',
            index=models.Index(fields=['is_active'], name='opportuniti_is_acti_342319_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesstage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_closed_won', True)), fields=('is_closed_won',), name='unique_closed_won_stage', violation_error_message="Only one 'Closed Won' stage allowed per tenant."),
        ),
        migrations.AddConstraint(
            model_name='salesstage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_closed_lost', True)), fields=('is_closed_lost',), name='unique_closed_lost_stage', violation_error_message="Only one 'Closed Lost' stage allowed per tenant."),
        ),
        migrations.AddIndex(
            model_name='opportunityhistory',
            index=models.Index(fields=['opportunity', '-created_at'], name='opportuniti_opportu_92df2d_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityhistory',
            index=models.Index(fields=['action'], name='opportuniti_action_0df995_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityhistory',
            index=models.Index(fields=['created_at'], name='opportuniti_created_a4627c_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='opportuniti_stage_i_29ff1f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner'], name='opportuniti_owner_i_c91c71_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['priority'], name='opportuniti_priorit_23713d_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='opportuniti_expecte_c56295_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['value'], name='opportuniti_value_8d3532_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['created_at'], name='opportuniti_created_5f72d6_idx'),
        ),
    ]
