# Generated by Django 5.2.5 on 2025-08-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the permission', max_length=100, unique=True)),
                ('codename', models.CharField(help_text="Unique code name for the permission (e.g., 'can_create_users')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('category', models.CharField(help_text="Permission category (e.g., 'User Management', 'Reports')", max_length=50)),
                ('is_super_user_only', models.BooleanField(default=False, help_text='True if this permission is only for super users (app owners/devs)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the role group (e.g., 'Admin', 'Manager')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role group')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this role group should be created by default in new tenants')),
                ('is_super_user_group', models.BooleanField(default=False, help_text='True if this role group is for super users only')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role group is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Group',
                'verbose_name_plural': 'Role Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='permissions.permission')),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.rolegroup')),
            ],
            options={
                'verbose_name': 'Role Group Permission',
                'verbose_name_plural': 'Role Group Permissions',
                'unique_together': {('role_group', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='rolegroup',
            name='permissions',
            field=models.ManyToManyField(help_text='Permissions assigned to this role group', through='permissions.RoleGroupPermission', to='permissions.permission'),
        ),
    ]
