# Generated by Django 4.2.7 on 2025-08-18 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuserrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantuserrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='tenant_permissions.tenantrole'),
        ),
        migrations.AddField(
            model_name='tenantuserrole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tenantrole',
            unique_together={('name', 'role_group')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantuserrole',
            unique_together={('user', 'role')},
        ),
    ]
